### PR TITLE
Add CHAI + RAJA launch integration test.

### PR DESCRIPTION
**Pull request by artv3**
Might be good to wait and bump RAJA to the upcoming path release: https://github.com/LLNL/RAJA/issues/1387

### CODE REVIEW

**Comment by adrienbernede** [comment]
This like relate to #218, https://github.com/LLNL/RAJA/pull/1384 and https://github.com/LLNL/RAJA/pull/1338.

**Comment by artv3** [comment]
Just updated the raja tpl to v2022.10.4, I think this should be good to go once it comes out green.

**Comment by artv3** [comment]
@adrienbernede @davidbeckingsale , I'm a bit confused about the failures. It looks like the gitlab builds use a different version of RAJA than that I pointed at.

**Comment by adrienbernede** [comment]
@artv3 the submodules are not used in the CI which is Spack based: it builds RAJA as a Spack package.
We’ll need both #218 and to update the RAJA Spack package so that Spack "sees" v2022.10.4 as the latest release.

**Comment by adrienbernede** [comment]
@artv3 @davidbeckingsale I’m on it, but lassen runners are out...

**Pull request merged**
