### PR TITLE
Replacing spack_configs by submodule

### PR DESCRIPTION
**Pull request by adrienbernede**
This pull request moves Spack configuration files used by Uberenv in a submodule.
The goal is to share those configuration files between projects, rather than duplicate them.

Spack configuration files will then be stored in https://github.com/LLNL/radiuss-spack-configs.

Linked to https://github.com/LLNL/RAJA/pull/903, https://github.com/LLNL/Umpire/pull/453.

### CODE REVIEW

**Comment by adrienbernede** [comment]
LGTM

**Comment by davidbeckingsale** [comment]
LGTM

**Comment by davidbeckingsale** [comment]
LGTM

**Comment by davidbeckingsale** [comment]
LGTM

**Comment by davidbeckingsale** [comment]
LGTM

**Comment by davidbeckingsale** [comment]
LGTM

**Comment by davidbeckingsale** [comment]
LGTM

**Comment by davidbeckingsale** [comment]
LGTM

**Comment by davidbeckingsale** [comment]
LGTM

**Comment by davidbeckingsale** [comment]
LGTM

**Comment by davidbeckingsale** [comment]
LGTM

**Comment by davidbeckingsale** [comment]
LGTM

**Comment by davidbeckingsale** [comment]
LGTM

**Comment by davidbeckingsale** [comment]
LGTM

**Comment by davidbeckingsale** [comment]
LGTM

**Comment by davidbeckingsale** [comment]
LGTM

**Comment by davidbeckingsale** [comment]
LGTM

**Comment by adrienbernede** [comment]
LGTM

**Comment by adrienbernede** [comment]
@davidbeckingsale What used to work (cuda build) does not work anymore. I'm guessing this is due to changes in CHAI (new version) gpu backends support.
There were changes in the upstream Spack package that we don't have locally.

**Comment by davidbeckingsale** [comment]
Replacing with #179

**Pull request closed without merging**
