### PR TITLE
[Woptim] update spack + update to rocm 5.7.1

### PR DESCRIPTION
**Pull request by adrienbernede**
Next steps are, in my opinion:
1. Merge LLNL/Umpire#857 -> done, we are now testing CHAI with umpire@develop ~= umpire@2024.02.0
2. Fix issues mentioned in #246 and now appearing in this PR. @adayton1 
3. Merge the present PR. 
4. Merge #243

@adayton1 @rhornung67, you both have created PRs in RADIUSS Spack Configs related to the 2024.02.0 releases. Both have different goals, Rich’s one (https://github.com/LLNL/radiuss-spack-configs/pull/90) aims to add the release to the packages, while Alan’s one (https://github.com/LLNL/radiuss-spack-configs/pull/89) aims to test CHAI with RAJA, Umpire and BLT at their release state.

I gathered those changes with mine and Chris White’s ones in a single, coherent, branch.

This branch is tested and vetted here.

### CODE REVIEW

**Review by rhornung67 — APPROVED** [review]

**Comment by adayton1** [comment]
@adrienbernede, I think this merge request will need to go in next. Can you get it up to date with develop, or would you like me to handle the merge conflicts?

**Comment by adrienbernede** [comment]
@adayton1 would you please have a look to the failing job on lassen ?

**Comment by adayton1** [comment]
> @adayton1 could you please give a look at the failing job on lassen ?

There seems to be a bad interplay with fmt coming through umpire and libcpp. RAJA and Umpire do not build with libcpp, so I made a change to allow failure for that test. I also disabled the failing docker test since Umpire and RAJA have that turned off as well. So I think if you merge in develop, I think all the tests should pass.

**Review by adayton1 — APPROVED** [review]
LGTM

**Comment by adrienbernede** [comment]
@adayton1 I got the CI green, however Umpire does build with libcpp: https://lc.llnl.gov/gitlab/radiuss/Umpire/-/jobs/1720331
I think there is something to be understood about the libcpp job that is related to CHAI.

**Comment by adayton1** [comment]
> @adayton1 I got the CI green, however Umpire does build with libcpp: https://lc.llnl.gov/gitlab/radiuss/Umpire/-/jobs/1720331 I think there is something to be understood about the libcpp job that is related to CHAI.

OK, I'm making a note to revisit the libcpp job.

**Pull request merged**
