### PR TITLE
Remove optional explicit synchronizes

### PR DESCRIPTION
**Pull request by adayton1**
* Removes ArrayManager::enableDeviceSynchronization and ArrayManager::disableDeviceSynchronization
* Instead, use the environment variables for device synchronization after all kernels (e.g. CUDA_LAUNCH_BLOCKING or HIP_LAUNCH_BLOCKING)

Follow up to #228

### CODE REVIEW

**Review by dtaller — APPROVED** [review]
Looks good to me.

Just check (email code leads) if there are any client codes that still use the depreciated functions, and let them know about this if needed.

**Comment by adayton1** [comment]
> Looks good to me.
> 
> Just check (email code leads) if there are any client codes that still use the depreciated functions, and let them know about this if needed.

I got the deprecated message in before the release and waited until after the release to push this change in. That way codes will have a whole release cycle before being impacted by this. That being said, this was only for debugging and I don't believe anyone besides us is using this.

**Comment by dtaller** [comment]
> > Looks good to me.
> > Just check (email code leads) if there are any client codes that still use the depreciated functions, and let them know about this if needed.
> 
> I got the deprecated message in before the release and waited until after the release to push this change in. That way codes will have a whole release cycle before being impacted by this. That being said, this was only for debugging and I don't believe anyone besides us is using this.

Good to hear, sounds good

**Review by robinson96 — APPROVED** [review]
LGTM

**Comment by adayton1** [comment]
@davidbeckingsale, can you take a review pass and merge if you think this is ready?

**Review by davidbeckingsale — APPROVED** [review]

**Pull request merged**
