### PR TITLE
Update to BLT v0.6.1

### PR DESCRIPTION
**Pull request by adayton1**
Update to BLT v0.6.1

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
Could you add the target export feature, see: https://github.com/LLNL/RAJA/pull/1542 and https://github.com/LLNL/Umpire/pull/857

**Comment by adayton1** [comment]
> Could you add the target export feature, see: [LLNL/RAJA#1542](https://github.com/LLNL/RAJA/pull/1542) and [LLNL/Umpire#857](https://github.com/LLNL/Umpire/pull/857)

Done.

**Review by rhornung67 — DISMISSED** [review]

**Comment by davidbeckingsale** [comment]
We don't have robust testing for this, but I'm concerned that the chai-config might need to also find raja/umpire/camp. 

I can add a test next week once I'm back, or if you want to take a crack this week, take a look at 'install-test' in Umpire/RAJA as an example: https://github.com/LLNL/Umpire/tree/develop/tests/install and https://github.com/LLNL/Umpire/blob/develop/scripts/gitlab/build_and_test.sh#L222-L235

**Comment by adayton1** [comment]
@adrienbernede, @rhornung67, I think there are a couple of prerequisites before this can be merged in.
- https://github.com/LLNL/radiuss-spack-configs/pull/89
- https://github.com/LLNL/CHAI/pull/245/files (since the latest radiuss-spack-configs needs an updated spack)

I think we need the newer radiuss-spack-configs to get the latest version of BLT anyway - the commit we just moved to does not have 0.6.1.

If you can think of a better way to do this, I'm open to hearing other ideas as well. I just don't want to have to hardcode the BLT version for every job and then undo that change after the release.

An alternative approach is to create local spack packages for just blt and chai, point to that first, then point to radiuss-spack-configs (I believe there is a way to pull from multiple spack repos). Then radiuss-spack-configs could be updated after the release of CHAI.

**Comment by adayton1** [comment]
Also, there's still some trouble with the Docker hip build and I know nothing about Docker. I think Umpire was having the same problem.

**Comment by rhornung67** [comment]
@adayton1 two things...first, the Docker HIP build is using 4.3.1 version of the compiler so a newer version may be better. second, it looks like the CMake is using the syntax `blt_hip`. i think it's supposed to be `blt::hip` now.

**Comment by adayton1** [comment]
> @adayton1 two things...first, the Docker HIP build is using 4.3.1 version of the compiler so a newer version may be better. second, it looks like the CMake is using the syntax `blt_hip`. i think it's supposed to be `blt::hip` now.

It looks like the latest available image from that repo is 5.1.3, so I'll try that. I grepped for blt_hip in chai and all its submodules, and it's not used anywhere. I'm really confused about where it is coming from.

**Pull request merged**
