### PR TITLE
Trying to add a user-defined callback that aid debugging and user-code integration

### PR DESCRIPTION
**Pull request by ajkunen**
This allows users of CHAI to derive their own ManagedArray types that add functionality (like being able to integrate into their own tracing/debugging facilities)

### CODE REVIEW

**Comment by ajkunen** [comment]
@davidbeckingsale I think this is done, but I was wondering what you thought about it?  It's made tracking which variables are moved and when.

**Comment by davidbeckingsale** [comment]
I just sent you an email about it :)

**Comment by ajkunen** [comment]
@davidbeckingsale assuming this passes travis, let me know what you think.

**Comment by davidbeckingsale** [comment]
Looks wonderful 😄  just one question above.

**Comment by davidbeckingsale** [comment]
@ajkunen - it's failing because you need to add implementations to the "thin" version.

**Comment by ajkunen** [comment]
@davidbeckingsale... right.  I'll do that now.

**Pull request merged**
