### PR TITLE
Remove implicit conversions

### PR DESCRIPTION
**Pull request by davidbeckingsale**

### CODE REVIEW

**Comment by robinson96** [comment]
While I think this needs to happen eventually, this will drastically increase the work needed to adopt this flavor of CHAI for my code, unless @rfhaque  has been hard at work removing points of implicit conversion from our source.

**Comment by davidbeckingsale** [comment]
@robinson96 - we are going to maintain a branch that has these conversions, along with the pick method and some other stuff, for you guys

**Comment by DavidPoliakoff** [comment]
FYI, the work with Laghos is also requiring these conversions

**Comment by davidbeckingsale** [comment]
Okay, closing.

**Pull request closed without merging**
