### PR TITLE
Support for AMD's HIP in CHAI

### PR DESCRIPTION
**Pull request by noelchalmers**
Tested on ROCm 2.2 with the following cmake command 

```cmake -DENABLE_CUDA=Off -DENABLE_HIP=On ..```

Some changes were required to use the most recent Umpire version. I'll need someone to check that these are ok.

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
@noelchalmers - just to let you know that with #76 we now have an up-to-date Umpire inside CHAI. I'll look at fixing the conflicts and testing this branch locally tomorrow.

**Comment by davidbeckingsale** [comment]
@noelchalmers - I've got this up to date with develop, can you test this out locally?

**Comment by noelchalmers** [comment]
Tested it out on my machine. Seems to compile and pass its unit tests. There's a new failed test in the umpire strategy_test though, so I'll look into that.

**Comment by davidbeckingsale** [comment]
We have identified the issue in Umpire and are working on a fix.

**Comment by davidbeckingsale** [comment]
@noelchalmers - I'm merging this, and will bump the Umpire submodule in a different PR. Thanks!

**Pull request merged**
