### PR TITLE
Fixup external camp detection

### PR DESCRIPTION
**Pull request by davidbeckingsale**

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
LGTM

**Comment by davidbeckingsale** [comment]
LGTM

**Comment by davidbeckingsale** [comment]
LGTM

**Comment by adrienbernede** [comment]
Hmm... interesting use case... the commit was already tested, so the CI won’t be triggered.

**Comment by adrienbernede** [comment]
We need to merge it.

**Pull request merged**
