### PR TITLE
Feature/gitlab ci

### PR DESCRIPTION
**Pull request by adrienbernede**
This PR adds CI on LC Gitlab for CHAI.

This is based on the CI setup of Umpire and RAJA:
- It is using Uberenv to drive Spack
- Spack builds the dependencies, if any, and generates the host-config files.
- These host-config files are used to configure the builds of CHAI.
- Finally, unit-test on CHAI are run.

Change compared to the travis workflow: RAJA is not build in CI to test integration with CHAI. Instead, the plan is to trigger RAJA pipeline and have it running with the corresponding version of CHAI.

### CODE REVIEW

**Comment by adrienbernede** [comment]
LGTM

**Comment by adrienbernede** [comment]
LGTM

**Comment by davidbeckingsale** [comment]
LGTM

**Comment by davidbeckingsale** [comment]
@adrienbernede - anything else we need to do here?

**Comment by adrienbernede** [comment]
@davidbeckingsale It can be merged. I’m working on "phase 2" :).

**Comment by davidbeckingsale** [comment]
> @davidbeckingsale It can be merged. I’m working on "phase 2" :).

Awesome, thanks @adrienbernede - I will merge once the tests finish.

**Comment by davidbeckingsale** [comment]
LGTM

**Pull request merged**
