### PR TITLE
Compiler wrappers + update packages + use spack environments

### PR DESCRIPTION
**Pull request by adrienbernede**
# Summary

- This PR updates the submodule RADIUSS Spack Configs

## Purpose

In RADIUSS Spack Configs:
- The compilers (wrappers) on Lassen have been updated to better support the use of gcc 8.3.1 toolchain.
- The local spack packages have been updated to be as close as possible to what we are pushing in https://github.com/spack/spack/pull/41375.
- We moved to Spack environments.

## Notes

Packages in RADIUSS Spack Configs still have some specific changes compared to the PR mentioned above.

### CODE REVIEW

**Comment by adrienbernede** [comment]
@adayton1 It is ready for review. I increased the lassen allocation in the last commit.

There is one thing we should discuss: jobs building with the develop version of the TPLs are failing because of a strange behavior in Spack.
I suggest we allow those jobs to fail and merge this while asking for help from Spack.

**Review by adayton1 — APPROVED** [review]
LGTM

**Comment by adayton1** [comment]
> @adayton1 It is ready for review. I increased the lassen allocation in the last commit.
> 
> There is one thing we should discuss: jobs building with the develop version of the TPLs are failing because of a strange behavior in Spack. I suggest we allow those jobs to fail and merge this while asking for help from Spack folks.

I'm fine with allowing failure for those particular jobs while we figure this out.

**Comment by adrienbernede** [comment]
@adayton1, done!

**Comment by adayton1** [comment]
> @adayton1, done!

Thanks!

**Review by adayton1 — APPROVED** [review]
LGTM

**Pull request merged**
