### PR TITLE
RAJA MultiView Integration

### PR DESCRIPTION
**Pull request by rchen20**
Added an interface to use RAJA::MultiView, with corresponding bump of RAJA version.

### CODE REVIEW

**Review by davidbeckingsale — APPROVED** [review]

**Comment by davidbeckingsale** [comment]
LGTM

**Comment by rchen20** [comment]
@davidbeckingsale It says that I'm not authorized to merge the PR.

**Comment by rchen20** [comment]
LGTM

**Comment by davidbeckingsale** [comment]
Thanks @rchen20 !

**Pull request merged**
