### PR TITLE
Add RAJA CI tests

### PR DESCRIPTION
**Pull request by davidbeckingsale**

### CODE REVIEW

**Comment by rhornung67** [comment]
Will CHAI tests be triggered on changes to RAJA develop or master?

**Comment by davidbeckingsale** [comment]
There is no way to link Travis tests based on inter-project dependencies 😞

**Comment by rhornung67** [comment]
Got it. That's a substantial improvement.  Thanks.

**Comment by davidbeckingsale** [comment]
Note that this also doesn't run tests with RAJA+CHAI enabled, but we could do that for the CPU only case.

**Pull request merged**
