### PR TITLE
Add the ability to enable or disable managed_ptr

### PR DESCRIPTION
**Pull request by adayton1**
* Adds a config option for controlling whether managed_ptr support is enabled/disabled.

### CODE REVIEW

**Review by robinson96 — COMMENTED** [review]
Do we want to keep managed_ptr in the includes so applications do not need to protect their include of managed_ptr with #ifdefs? Maybe with a #warning/#error to let people know they haven't protected their #include statement and an explicit naming of the appropriate macro to use so the compiler warning / error is more friendly?

**Comment by adayton1** [comment]
Good idea, Peter. I just added a `#error` when managed_ptr.hpp is included and it is not supported. Let me know what you think.

**Review by robinson96 — APPROVED** [review]
LGTM

**Review by davidbeckingsale — APPROVED** [review]
👍

**Pull request merged**
