### PR TITLE
Bump RAJA to v0.12.0 and update plugin

### PR DESCRIPTION
**Pull request by MrBurmark**
Update the CHAI RAJA plugin to work correctly with the changed RAJA plugin interface.
PreCapture and PostCapture calls have been added and the CHAI RAJA plugin now uses these instead of PreLaunch and PostLaunch.
The plugin tests have also been cleaned up a bit.

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
Thanks for this @MrBurmark - I am going to wait until the RAJA release comes out so that we can point at a tagged version in the submodule.

**Comment by MrBurmark** [comment]
The pluginLinker in RAJA and pluginLinker in CHAI now conflict, suggestions?

**Comment by davidbeckingsale** [comment]
> The pluginLinker in RAJA and pluginLinker in CHAI now conflict, suggestions?

Namespacing? Although the pluginLinker is in an anonymous namespace so it shouldn't conflict should it?

**Comment by MrBurmark** [comment]
I think the problem comes when both headers are included in the same file. I'll add namespacing inside the anonymous namespace.

**Comment by davidbeckingsale** [comment]
LGTM

**Pull request merged**
