### PR TITLE
changed add_sphinx_target to blt_add_sphinx_target

### PR DESCRIPTION
**Pull request by rrsettgast**
was getting a build failure as name for add_sphinx_target has changed to blt_add_sphinx_target

### CODE REVIEW

**Comment by rrsettgast** [comment]
@davidbeckingsale went down a little rabbit hole trying to pass the tests. Umpire requires a fortran compiler, and it seems hard-coded, but there is no fortran compiler on the travis test containers. I would just add the fortran requirement of the BLT flag ENABLE_FORTRAN==ON. What is the right thing to do?

**Comment by davidbeckingsale** [comment]
Oh dear - it's because Umpire has `Fortran` in the `project` command, even though whether or not we build the Fortran interface is controlled by `ENABLE_FORTRAN`.

I'll fix it.

**Comment by davidbeckingsale** [comment]
Can you revert this PR to commit 1a24e44 then I'll merge it.

**Comment by rrsettgast** [comment]
Done.

**Comment by davidbeckingsale** [comment]
Thanks!

**Pull request merged**
